In [8]:
import pandas as pd

In [9]:
df=pd.read_csv("/content/student_performance.csv")
print("Dataset loaded successfully")

Dataset loaded successfully

In [10]:
#To View first 5 rows
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [11]:
#To view last 5 rows
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [12]:
df[df['attendance_percentage']>90]

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [13]:
#shape[0]-means print the number of rows
#shape[1]-means print the number of columns
print("Shape of dataset:",df.shape)
print("Number of rows:",df.shape[0])
print("Number of columns:",df.shape[1])

Shape of dataset: (30, 13)
Number of rows: 30
Number of columns: 13

In [14]:
#tolist hepls to convert from pandas index object into a regular python list
print("Columns in my dataset:")
print(df.columns.tolist())
print("Column names without tolist:")
print(df.columns)

Columns in my dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']
Column names without tolist:
Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year'],
      dtype='object')

In [15]:
#To see the statics report of the particular dataset
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [16]:
#To find the datatypes of the columns in the dataset
print("Data types:")
print(df.dtypes)

Data types:
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [17]:
#To check for the missing values in the dataset
print("Missing values in each column:")
print(df.isnull().sum())
print("\nTotal missing values:",df.isnull().sum().sum())

Missing values in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

Total missing values: 0

In [18]:
print("Student Names:")
print(df['name'])

Student Names:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [19]:
print("Attendence_percentage")
print(df['attendance_percentage'])

Attendence_percentage
0     92
1     87
2     78
3     95
4     90
5     72
6     85
7     96
8     68
9     98
10    83
11    80
12    88
13    91
14    75
15    93
16    65
17    94
18    77
19    89
20    74
21    97
22    70
23    86
24    91
25    82
26    87
27    73
28    84
29    95
Name: attendance_percentage, dtype: int64

In [20]:
print("City of students:")
print(df['city'])

City of students:
0                 Mumbai
1              Ahmedabad
2                  Delhi
3              Hyderabad
4                  Kochi
5                   Pune
6              Bangalore
7                Lucknow
8               Varanasi
9                Kolkata
10               Chennai
11                Jaipur
12                Mysore
13              Thrissur
14                Bhopal
15                  Agra
16                 Patna
17                Nagpur
18              Dehradun
19            Chandigarh
20    Thiruvananthapuram
21                 Surat
22             Allahabad
23                Kanpur
24               Kolkata
25                 Kochi
26               Lucknow
27    Thiruvananthapuram
28                Indore
29                  Agra
Name: city, dtype: object

In [21]:
print("Departments in this dataset:")
print(df['department'].unique())

Departments in this dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [22]:
#To count how many students in the particular department
print("How many students per department:")
print(df['department'].value_counts())

How many students per department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [23]:
cs_students=df[df['department']=='Computer Science']
print(f"Number of Computer Science Students:{len(cs_students)}")
print("\nComputer Science Students:")
print(cs_students[['name','math_score','programming_score','attendance_percentage']])

Number of Computer Science Students:13

Computer Science Students:
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
1      Priya Patel          76                 79                     87
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
12      Suresh Rao          83                 88                     88
14     Ajay Tiwari          71                 76                     75
17  Swati Kulkarni          90                 92                     94
19    Nisha Kapoor          79                 83                     89
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
26   Gaurav Shukla          84                 87                     87
29  Akanksha Yadav          91                 94                     95

In [24]:
high_attendance=df[df['attendance_percentage']>90]
print(f"Students with attendence above 90%:{len(high_attendance)}")
print(high_attendance[['name','department','attendance_percentage']])

Students with attendence above 90%:10
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [25]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
top_student=df.loc[df['total_score'].idxmax()]
print("Top Student:")
print(f"Name:{top_student['name']}")
print(f"Department:{top_student['department']}")
print(f"Total Score:{top_student['total_score']}")
print(f"Attendance:{top_student['attendance_percentage']}%")

Top Student:
Name:Ananya Das
Department:Computer Science
Total Score:371
Attendance:98%

In [26]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)
print("Average Total Score by department:")
print(dept_avg)

Average Total Score by department:
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [27]:
df_sorted=df.sort_values(by='total_score',ascending=False)
print("Top 10 Students by Total Score:")
print(df_sorted[['name','department','total_score','attendance_percentage']].head(10))

Top 10 Students by Total Score:
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          371                     98
21     Tanvi Mehta  Computer Science          367                     97
29  Akanksha Yadav  Computer Science          365                     95
4       Arjun Nair  Computer Science          356                     90
7      Divya Singh  Computer Science          356                     96
17  Swati Kulkarni  Computer Science          354                     94
24       Amit Bose  Computer Science          336                     91
12      Suresh Rao  Computer Science          334                     88
19    Nisha Kapoor  Computer Science          327                     89
0     Aarav Sharma  Computer Science          326                     92

How many students are from the electronics department?

In [28]:
count=df.groupby('department')['name'].count()
ec_stu=df[df['department']=='Electronics']
print(f"Number of students in Electronics department:{len(ec_stu)}")

Number of students in Electronics department:6

What is the average attendance of female students?

In [29]:
female_students = df[df['gender'] == 'Female']
average_attendance_female = female_students['attendance_percentage'].mean()
print(f"Average attendance for female students: {average_attendance_female:.2f}%")

Average attendance for female students: 88.53%

Who is the student with the lowest programming score?

In [30]:
low=df.loc[df['programming_score'].idxmin()]
print("Student with lowest programming score:")
print(f"Name:{low['name']}")
print(f"Programming Score:{low['programming_score']}")

Student with lowest programming score:
Name:Manoj Pandey
Programming Score:38

How many students scored above 80 in maths?

In [31]:
newc=df[df['math_score']>80]
print(f"Number of students with math score above 80:{len(newc)}")

Number of students with math score above 80:11

What is the average total_score for students with attendence above 90%?

In [32]:
newa=df[df['attendance_percentage']>90]
newav=newa['total_score'].mean()
print(f"Average total score for students attendance above 90%:{newav:.2f}")

Average total score for students attendance above 90%:335.80

# MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Pythin to analyze student data and generate a detailed report.

# Dataset Columns:

name

gender

department

math_score

programming_score

attendance_percentage

total_score

# Tasks to perform:
1. Display Project title

 Print a formatte title with seperator lines

2. Dataset Overview

Display:

-Total number of students

-total number of columns

-number of unique departments

3. Department wise analysis

display the count of students in each department.

4. Score Analysis

Find and Display:

-highest math score

-lowest math score

-avg math score

-avg programming score

-avg attendance percentage

5. Gender wise Analysis

Calculate and display avg total score by gender

6. Top performers

Display top 5 students based on total score.

Show:

-Student name

-Department

-total score

7. Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Atendance Percentage

If all students have attendance above 75%, print a suitable message.

# Concepts to use:

-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional Statements, f-strings

### Student Data Explorer: Project Title

In [33]:
print("=" * 40)
print("     Student Performance Explorer   ")
print("=" * 40)

========================================
     Student Performance Explorer
========================================

### Task 2: Dataset Overview

In [34]:
print(f"Total number of students: {len(df)}")
print(f"Total number of columns: {df.shape[1]}")
print(f"Number of unique departments: {df['department'].nunique()}")

Total number of students: 30
Total number of columns: 14
Number of unique departments: 4

### Task 3: Department-wise Analysis

In [35]:
print("Count of students in each department:")
print(df['department'].value_counts())

Count of students in each department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

### Task 4: Score Analysis

In [36]:
print(f"Highest Math Score: {df['math_score'].max()}")
print(f"Lowest Math Score: {df['math_score'].min()}")
print(f"Average Math Score: {df['math_score'].mean():.2f}")
print(f"Average Programming Score: {df['programming_score'].mean():.2f}")
print(f"Average Attendance Percentage: {df['attendance_percentage'].mean():.2f}%")

Highest Math Score: 95
Lowest Math Score: 56
Average Math Score: 76.07
Average Programming Score: 67.60
Average Attendance Percentage: 84.50%

### Task 5: Gender-wise Analysis

In [37]:
print("Average Total Score by Gender:")
print(df.groupby('gender')['total_score'].mean().round(2))

Average Total Score by Gender:
gender
Female    310.67
Male      280.67
Name: total_score, dtype: float64

### Task 6: Top Performers

In [38]:
df_sorted_total = df.sort_values(by='total_score', ascending=False)
print("Top 5 Students by Total Score:")
print(df_sorted_total[['name', 'department', 'total_score']].head(5))

Top 5 Students by Total Score:
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

### Task 7: Attendance Analysis

In [39]:
low_attendance_students = df[df['attendance_percentage'] < 75]

if not low_attendance_students.empty:
    print("Students with attendance below 75%:")
    print(low_attendance_students[['name', 'department', 'attendance_percentage']])
else:
    print("All students have attendance above 75%.")

Students with attendance below 75%:
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73

Practice Questions

Try solving these on your own. Answers are provided in the next section.

Question 1:

How many students are from the Electronics department?

Question 2:

What is the average attendance of female students?

Question 3:

Who is the student with the lowest programming score?

Question 4:

How many students scored above 80 in math?

Question 5:

What is the average total_score for students with attendance above 90%?

### Question 1: How many students are from the Electronics department?

In [40]:
electronics_students_count = df[df['department'] == 'Electronics'].shape[0]
print(f"Number of students from the Electronics department: {electronics_students_count}")

Number of students from the Electronics department: 6

### Question 2: What is the average attendance of female students?

In [41]:
female_students_df = df[df['gender'] == 'Female']
average_attendance_female = female_students_df['attendance_percentage'].mean()
print(f"Average attendance of female students: {average_attendance_female:.2f}%")

Average attendance of female students: 88.53%

### Question 3: Who is the student with the lowest programming score?

In [42]:
lowest_programming_score_student = df.loc[df['programming_score'].idxmin()]
print("Student with the lowest programming score:")
print(f"Name: {lowest_programming_score_student['name']}")
print(f"Programming Score: {lowest_programming_score_student['programming_score']}")

Student with the lowest programming score:
Name: Manoj Pandey
Programming Score: 38

### Question 4: How many students scored above 80 in maths?

In [43]:
students_above_80_math = df[df['math_score'] > 80].shape[0]
print(f"Number of students who scored above 80 in maths: {students_above_80_math}")

Number of students who scored above 80 in maths: 11

### Question 5: What is the average total_score for students with attendance above 90%?

In [44]:
high_attendance_students_df = df[df['attendance_percentage'] > 90]
average_total_score_high_attendance = high_attendance_students_df['total_score'].mean()
print(f"Average total score for students with attendance above 90%: {average_total_score_high_attendance:.2f}")

Average total score for students with attendance above 90%: 335.80